// ///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserProfile {
/*
{
  "primary_email": "pranjalpiya10@gmail.com",
  "full_name": "Pranjal Piya",
  "level": "0",
  "phone_number": "9845023754",
  "phone_verify": "0",
  "current_address": "Chitwan",
  "permanent_address": "Kathmandu",
  "point_counter": "0",
  "reg_date": "2021-09-06",
  "about": "My Name is Pranjal Piya. I am an Undergraduate Student at Islington College pursuing my bachelor's degree in Information Technology",
  "image": "https://ikreate.com.np/assets/img/user/intern/S7yWwEQBOzbqnaTRLKD1jruMHGpgisUtV.jpg"
} 
*/

  String? primaryEmail;
  String? fullName;
  String? level;
  String? phoneNumber;
  String? phoneVerify;
  String? currentAddress;
  String? permanentAddress;
  String? pointCounter;
  String? regDate;
  String? about;
  String? image;

  UserProfile({
    this.primaryEmail,
    this.fullName,
    this.level,
    this.phoneNumber,
    this.phoneVerify,
    this.currentAddress,
    this.permanentAddress,
    this.pointCounter,
    this.regDate,
    this.about,
    this.image,
  });
  UserProfile.fromJson(Map<String, dynamic> json) {
    primaryEmail = json["primary_email"]?.toString();
    fullName = json["full_name"]?.toString();
    level = json["level"]?.toString();
    phoneNumber = json["phone_number"]?.toString();
    phoneVerify = json["phone_verify"]?.toString();
    currentAddress = json["current_address"]?.toString();
    permanentAddress = json["permanent_address"]?.toString();
    pointCounter = json["point_counter"]?.toString();
    regDate = json["reg_date"]?.toString();
    about = json["about"]?.toString();
    image = json["image"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["primary_email"] = primaryEmail;
    data["full_name"] = fullName;
    data["level"] = level;
    data["phone_number"] = phoneNumber;
    data["phone_verify"] = phoneVerify;
    data["current_address"] = currentAddress;
    data["permanent_address"] = permanentAddress;
    data["point_counter"] = pointCounter;
    data["reg_date"] = regDate;
    data["about"] = about;
    data["image"] = image;
    return data;
  }
}

class User {
/*
{
  "status": "success",
  "message": "Internship Profile",
  "profile": {
    "primary_email": "pranjalpiya10@gmail.com",
    "full_name": "Pranjal Piya",
    "level": "0",
    "phone_number": "9845023754",
    "phone_verify": "0",
    "current_address": "Chitwan",
    "permanent_address": "Kathmandu",
    "point_counter": "0",
    "reg_date": "2021-09-06",
    "about": "My Name is Pranjal Piya. I am an Undergraduate Student at Islington College pursuing my bachelor's degree in Information Technology",
    "image": "https://ikreate.com.np/assets/img/user/intern/S7yWwEQBOzbqnaTRLKD1jruMHGpgisUtV.jpg"
  }
} 
*/

  String? status;
  String? message;
  UserProfile? profile;

  User({
    this.status,
    this.message,
    this.profile,
  });
  User.fromJson(Map<String, dynamic> json) {
    status = json["status"]?.toString();
    message = json["message"]?.toString();
    profile = (json["profile"] != null)
        ? UserProfile.fromJson(json["profile"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["message"] = message;
    if (profile != null) {
      data["profile"] = profile!.toJson();
    }
    return data;
  }
}
